### PR TITLE
Replace QuTiP utils by library utils in tests (+ various minor fixes)

### PR DESCRIPTION
**Pull request by PierreGuilmin**

### CODE REVIEW

**Review by gautierronan — DISMISSED** [review]

**Comment by gautierronan** [comment]
Where do you see that the tests are failing? But no I'm not sure why. Would need to run some tests I guess to make sure my previous PR didn't introduce a bug.

**Comment by PierreGuilmin** [comment]
> Where do you see that the tests are failing? But no I'm not sure why. Would need to run some tests I guess to make sure my previous PR didn't introduce a bug.

I run them locally, ok I will investigate further.

**Comment by PierreGuilmin** [comment]
@gautierronan it was a stupid bug, see 4ed4236801244e4f1e9edb500cffbb964cd17031. 😅

**Comment by PierreGuilmin** [comment]
That's not very good practice but I'm adding a few random very small fixes to this PR.

**Pull request merged**
