### PR TITLE
No autograd in base solver

### PR DESCRIPTION
**Pull request by pierreguilmin**
Non-differentiable solvers are now supported.

### CODE REVIEW

**Comment by pierreguilmin** [comment]
Note that there is a minor design flaw with the current code: one cannot implement a solver which only supports gradient by the adjoint and not autograd. I don't see any use case for this so... osef 😋

**Comment by abocquet** [comment]
Is there a case for this? All solvers are differentiable at least through autograd no?

**Comment by pierreguilmin** [comment]
No indeed, but if you want to quickly test a solver (say plug in some numpy or qutip code or some new torch diagonalization magic which does not support autograd for complex, or analytic gradients with GRAPE) this is very useful 😋

**Review by gautierronan — APPROVED** [review]
Gucci

**Pull request merged**
