### PR TITLE
Add logo to readme

### PR DESCRIPTION
**Pull request by gautierronan**
(text is in bordeau to account for light and dark github page)

### CODE REVIEW

**Comment by gautierronan** [comment]
Also changed the text color following (mean) comments by my girlfriend :$

**Comment by PierreGuilmin** [comment]
2001 x 401 🧐 😋

**Comment by gautierronan** [comment]
> 2001 x 401 🧐 😋

Yes sorry, I said 2000 x 400 to illustrator, but he exported to one more pixel. Not sure why. Is it important?

**Comment by PierreGuilmin** [comment]
It's fine, it's just more common I don't really know why I'm just copying other 🤷‍♂️

**Review by PierreGuilmin — APPROVED** [review]

**Comment by PierreGuilmin** [comment]
I'll let you have the pleasure to merge this one 😉

**Pull request merged**
